### ISSUE TITLE
v1.1 not published to nuget

### ISSUE THREAD

**Issue by SethDG** [CorrelatorSharp/CorrelatorSharp.AspNetCore.Mvc#3]
Can you do me a favor and publish v1.1 to nuget?  I had downloaded the current nuget package (v1.0) and couldn't figure out why the Name property wouldn't work.  I realize now that functionality was added in v1.1 but it took me awhile to figure that out.

Thanks!

**Comment by SethDG** [comment]
I apologize, I realize now that the person publishing the code to nuget is likely a different person than the maintainer of this repository.  I have contacted the owner of the nuget package through the nuget site.  I'm going to close this issue.

**Comment by jasond-s** [comment]
Appveyor should have released the new version after building. Seems there is an error in the Appveyor build. 

Will take a look ASAP. Seems some issue with tags. It's all a bit black magic to me and from what I know, should have worked.

**Comment by jasond-s** [comment]
There was an erroneous tag `1.0.0` created that seems to have been causing an issue. I have cleaned up the tags and releases and appveyor is now correctly building. 

However, the nuget package is failing to upload from appveyor as there seems to be an issue with the certificate at https://nuget.smbsrc.net.... again.

https://github.com/NuGet/Home/issues/6082

Will close once the cert issue is fixed and appveyor can release the code correctly. If there is a desperate need for this version to be available might consider manually pushing the package.

**Comment by SethDG** [comment]
Thank you so much for digging into this problem

I don't know about anyone else, but there is no desperate need from me.  It is up to you when and how you want to solve this problem.  I am doing fine just compiling from source and using v1.1 that way.

**Comment by jasond-s** [comment]
Seems that the certificate issue has been fixed. Have released the new version to nuget.

**Comment by SethDG** [comment]
Thanks a lot!
